jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Run shell commands
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/githubtraining/hellogitworld.git
